spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

the-meal-db:
  base-url: https://www.themealdb.com/api/json/v1/1
  complexity:
    easy: 7
    medium: 10

app:
  security:
    jwt:
      access:
        secret: SECRET_KEY_FOR_ACCESS_TOKEN
        expiration-ms: 900000 # 15 min
      refresh:
        secret: SECRET_KEY_FOR_REFRESH_TOKEN
        expiration-ms: 1296000000 # 15 days
  frontend:
    url: http://localhost:3000