spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/int20h_2023_tt # local url provided by docker container
    username: root                                  # local username provided by docker container
    password: root                                  # local password provided by docker container
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

the-meal-db:
  base-url: https://www.themealdb.com/api/json/v1/1
  complexity:
    easy: 7
    medium: 10

app:
  security:
    jwt:
      access:
        secret: SECRET_KEY_FOR_ACCESS_TOKEN
        expiration-ms: 900000 # 15 min
      refresh:
        secret: SECRET_KEY_FOR_REFRESH_TOKEN
        expiration-ms: 1296000000 # 15 days